#!/bin/bash
wget https://github.com/dylanaraps/neofetch/archive/refs/tags/7.1.0.tar.gz
mkdir /tmp/lmt
mv '7.1.0.tar.gz' /tmp/lmt
cd /tmp/lmt/
tar xpf 7.1.0.tar.gz
cd neofetch-7.1.0/
make
make install
cd
rm -rf /tmp/lmt
